# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c42a5470ee34ec09e06f5af81d29f2d4dda41847752900e35f71c6b641db407224663246844abcbf811efedbe8a637ca5b8b7d2f5ab8383d9b89f4d05e0f1a51

test:
  secret_key_base: 24729a27ccdb5441ecc62d0ecced8160cd9d11f7d5ce8353cffbffc79b56dd7856295a847eb9ed6d1766c8cb96e941183372f309be9f1be4ea6a8dc84a7daa66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
